library(stringr)
library(dplyr)
library(purrr)

#' footnotes appear at the bottom of a page as single number
#' that starts and ends the line
#' @param page a page of text generated by `pdf_text()`
#' @return a list of footnotes in the page and their indices
extract_footnotes <- function(page) {
 
  if (any(str_detect(page, "^[ 0-9]+$"))) {
    footnote_start <- c(
        str_which(page, "^[ 0-9]+$"),
        length(page) - 1
      )
    
    footnote_length <- c(diff(footnote_start) - 1, NA)
    
    footnote_position <- 
      data_frame(footnote_start, footnote_length) %>% 
        mutate(footnote_end = footnote_start + footnote_length) %>%
        filter(!is.na(footnote_length))
    
    footnote_text <- footnote_position %>%   
      map2_chr(
        .x = .$footnote_start, .y = .$footnote_end,
        .f = ~str_c(page[(.x+1):.y], collapse = " ")
      )
    
    footnote_index <- footnote_position$footnote_start %>% 
      map_chr(~page[[.x]])
    
    list(
      index = footnote_index,
      text  = footnote_text
      ) %>% map(str_squish)
    }
}

#' replace footnotes inline with markdown style footnote indicators.
#' Exclude the words fig and any month abbreviations
#' @param page a page of text generated by `pdf_text()`
#' @return a page with all inline footnotes replaced with markdown style footnotes
markdownify_footnotes <- function(page) {

  str_replace_all(
    page,
    c("(((?<!fig|Jan|Feb|Mar|Apr|Aug|Sept|Oct|Nov|Dec)\\.) ([0-9]+))" = "\\2 \\[\\^\\3\\]")
    )
  }

#' remove the footnotes from the bottom of the page
#' @param page a page of text generated by `pdf_text()`
#' @return a page of text with no footnote text
clip_footnotes <- function(page) {
  if (any(str_detect(page, "^[ 0-9]+$"))) {
    footnote_start <- min(str_which(page, "^[ 0-9]+$"))
    page[1:footnote_start - 1]
    }
  
}